PkvStore Resource fix
johanhelsing/bevy_pkv pull request #16
Opened 2022-11-13 01:29 UTC by Aultus-defora

My attempt at fixing PkvStore not being a resource. Not sure if it is possible to add something smaller than bevy_ecs to dependencies.

2022-11-13 09:27 UTC, johanhelsing commented
Thanks for the PR!

I wonder if it'd be possible to make bevy an optional dependency?

Something like:

```rust
#[derive(Debug)]
#[cfg_attr(feature = "bevy", derive(Resource))]
struct PkvStore {
```

Also, not sure what the practical difference is between importing bevy_ecs vs. importing `bevy` with `default-features = false` and then enable the features needed? I usually do the latter, but it would be good to know whether one approach has advantages over the other.

2022-11-13 16:48 UTC, Aultus-defora commented
I am not sure what feature(s) is(are) enough to make #[derive(Resource)] work.

2022-11-13 18:32 UTC, Aultus-defora commented
Now I use features to limit the Resource use, used cargo clippy to make linting good, also updated table — in 0.9 one has to at the very least create new struct with Resource to have PkvStore inside of a resource which is a hassle, this should solve that issue

2022-11-13 21:16 UTC, johanhelsing commented on README.md
> +|0.8|0.6, main|
```suggestion
|0.9|0.6, main|
```

2022-11-13 21:18 UTC, johanhelsing commented
Nice, this was exactly what I had in mind. Just a small error in the version table.

2022-11-13 22:15 UTC, Aultus-defora commented
I merged the version table fix. Also confirmed that the `#[derive(Resource)]` works.

2022-11-14 07:56 UTC, johanhelsing requested changes
Aside from fixing the linting error. with cfg attributes, I find it cleaner to just fully qualify types

2022-11-14 07:56 UTC, johanhelsing commented on src/lib.rs
> +
```suggestion
```

2022-11-14 07:56 UTC, johanhelsing commented on src/lib.rs
> +#[cfg_attr(feature = "bevy", derive(Resource))]
```suggestion
#[cfg_attr(feature = "bevy", derive(bevy_ecs::prelude::Resource))]
```

2022-11-14 07:57 UTC, johanhelsing approved these changes

2022-11-14 08:04 UTC, merged