feat: Pickle DB Backend Support
johanhelsing/bevy_pkv pull request #37
Opened 2023-04-18 06:15 UTC by nx2k3

This adds support for **Pickle DB** alternative backend for non-wasm based environments.
#32

2023-04-18 06:18 UTC, nx2k3 commented
Is error handling done right

2023-04-18 06:41 UTC, johanhelsing reviewed
Thanks!

Apart from the unused variant, I think the error handling is right, in the sense that it follows the current convention of the other backends. We might want to revisit that though, but not in this PR.

There are some whitespace formatting issues, most of them should go away by running `cargo fmt`, but the toml ones you'll have to fix manually.

Other than that, it looks great to me :)

2023-04-18 06:41 UTC, johanhelsing commented on Cargo.toml
> +pickledb=["dep:pickledb"]
```suggestion
pickledb = ["dep:pickledb"]
```
 Please follow surrounding whitespace style, repeats.

2023-04-18 06:41 UTC, johanhelsing commented on src/pickledb_store.rs
> +    PickleDb(#[from] pickledb::error::Error),
I think this variant is unused?

Also, it says rocksdb, not picledb.

2023-04-18 06:41 UTC, johanhelsing commented on src/pickledb_store.rs
> +    /// An internal error from the rocksdb crate
```suggestion
    /// An internal error from the `pickledb` crate
```

2023-04-18 06:58 UTC, johanhelsing commented on src/lib.rs
> +compile_error!("the \"rocksdb\" ,\"pickledb\" and \"sled\" features may not be enabled at the same time");
```suggestion
compile_error!("the \"rocksdb\", \"pickledb\" and \"sled\" features may not be enabled at the same time");
```

2023-04-18 06:58 UTC, johanhelsing commented on src/lib.rs
> +compile_error!("either the \"rocksdb\",\"pickledb\" or \"sled\" feature must be enabled on native");
```suggestion
compile_error!("either the \"rocksdb\", \"pickledb\" or \"sled\" feature must be enabled on native");
```

2023-04-19 05:02 UTC, johanhelsing approved these changes

2023-04-19 05:02 UTC, johanhelsing commented on src/pickledb_store.rs
> +pub struct PickleDBStore {
One very minor nitpick: We follow the rust convention that abbreviations are pascal case, so PickleDb.

This is just internal api, so fix it you feel like it :)

Thanks for the contribution!

2023-04-20 14:33 UTC, nx2k3 commented
> Are the tests passing locally for you?

yes they are passing

2023-04-20 14:35 UTC, johanhelsing commented
Hmm.. okay. We need to figure out why they are failing in ci, then. Which os are you on?

2023-04-20 14:47 UTC, nx2k3 commented
> Hmm.. okay. We need to figure out why they are failing in ci, then. Which os are you on?

arch linux wsl
![image](https://user-images.githubusercontent.com/71603665/233402833-057ba31f-0b7c-49af-b6e8-b24e8ced4bd3.png)

2023-04-20 17:17 UTC, johanhelsing commented
Okay i tried on windows, passing there as well.

Maybe it's some parent directory that needs to be created or something? What happens if you delete the app folder? Do the tests fail then?

Guess i could try this myself, but on the go now

2023-04-21 02:04 UTC, nx2k3 commented
hey i think [dump function](https://github.com/seladb/pickledb-rs/blob/fcce2a32e1cbfc57fc8aacd3f1b09870ba59eacb/src/pickledb.rs#L366) is causing error

2023-05-06 08:57 UTC, johanhelsing requested changes
I think pickledb is a really good fit for a new default backend on native... but we need to fix that test. If anyone has the time to look into it, it would be much appreciated!

2023-05-06 09:02 UTC, StaffEngineer commented
@johanhelsing I looked into pickledb source code, I might be wrong but it seems it loads the whole DB into memory which is a huge blocker for me to use.

2023-05-06 09:05 UTC, johanhelsing commented
Ah, bummer. In either case, I don't plan on getting rid of the other backends.

Other suggestions for maintained rust-only native backends are welcome.

2023-10-08 07:40 UTC, nx2k3 commented
hey I think its better to close this PR as redb support was added

2025-04-17 14:14 UTC, closed without merging